meta:
  image: pojntfx/dhcpdd:latest
  dev: false
  debugPort: 31441
  debugNodePort: 31441
  target: "{{ .DIBS_TARGET }}"
  platform: "{{ .TARGETPLATFORM }}"
  debug: "{{ .DIBS_DEBUG }}"

resources:
  memory: "128Mi"
  cpu: "256m"
  maxReplicas: 10

ingress:
  loadBalancerPorts:
    - 67
  nodePort: 31240
  domain: dhcpdd.felix.pojtinger.com
  path: /
